mod adapter;
mod bridge;
mod catalog;
mod chat_tools_bridge;
mod contract;
mod deepseek_bridge;
mod errors;
mod fallback;
mod gemini_bridge;
mod models;
mod replay_cases;
mod surface;
#[cfg(test)]
mod tests;
mod translator;
mod translators;
mod usage;

pub use adapter::{StaticProviderAdapter, provider_adapter};
pub use bridge::{
    provider_core_chat_compatible_created_at, provider_core_chat_compatible_responses_usage,
    provider_core_chat_compatible_responses_value_from_chat_value,
    provider_core_chat_compatible_rtk_wrapped_tool_arguments,
    provider_core_chat_compatible_tool_call_thought_signature,
    provider_core_chat_compatible_validate_top_level_request_shape, provider_core_lossless_body,
    provider_core_rewritten_body, provider_core_rewritten_json_value,
    provider_core_split_flat_namespace_tool_name,
};
pub use catalog::{
    ProviderCatalogEntry, ProviderCatalogFeatureFlags, provider_catalog_entries,
    provider_catalog_entries_for, provider_catalog_entry, provider_catalog_json,
    provider_model_catalog_json, provider_model_json,
};
pub use chat_tools_bridge::{
    provider_core_chat_request_body_without_web_search_options,
    provider_core_chat_tool_choice_from_responses_request,
    provider_core_chat_tools_from_responses_request,
    provider_core_chat_web_search_options_from_responses_request,
    provider_core_flatten_namespace_tool_name,
};
pub use contract::{
    PROVIDER_CONTRACT_PROVIDERS, ProviderAdapterContractSpec, ProviderEndpointContractSpec,
    provider_adapter_contract_matrix, provider_adapter_contract_spec,
    provider_capabilities_markdown,
};
pub use deepseek_bridge::{
    deepseek_provider_core_apply_reasoning_from_responses_request,
    deepseek_provider_core_apply_strict_function_schema,
    deepseek_provider_core_chat_assistant_messages_from_response_value,
    deepseek_provider_core_chat_role, deepseek_provider_core_dedup_and_validate_function_tools,
    deepseek_provider_core_ensure_json_prompt_instruction,
    deepseek_provider_core_first_function_call_output_call_id,
    deepseek_provider_core_function_tool_name, deepseek_provider_core_history_has_system_message,
    deepseek_provider_core_history_has_tool_call,
    deepseek_provider_core_insert_primitive_request_fields,
    deepseek_provider_core_is_generic_function_tool, deepseek_provider_core_json_string,
    deepseek_provider_core_json_string_at_path, deepseek_provider_core_merge_response_metadata,
    deepseek_provider_core_message_signatures,
    deepseek_provider_core_messages_from_responses_request,
    deepseek_provider_core_normalize_assistant_tool_call_content,
    deepseek_provider_core_normalize_thinking_tool_call_messages,
    deepseek_provider_core_note_thinking_tool_choice_omission,
    deepseek_provider_core_push_message_from_responses_item,
    deepseek_provider_core_reject_beta_completion_fields,
    deepseek_provider_core_reject_unsupported_request_fields,
    deepseek_provider_core_repair_tool_call_adjacency, deepseek_provider_core_request_body,
    deepseek_provider_core_response_format_from_responses_request,
    deepseek_provider_core_response_metadata_from_responses_request,
    deepseek_provider_core_responses_content_text,
    deepseek_provider_core_responses_content_text_value,
    deepseek_provider_core_rtk_wrapped_tool_arguments, deepseek_provider_core_simple_request,
    deepseek_provider_core_stop_from_responses_request, deepseek_provider_core_system_message,
    deepseek_provider_core_thinking_enabled, deepseek_provider_core_tool_call_ids,
    deepseek_provider_core_tool_call_thought_signature,
    deepseek_provider_core_tool_name_from_tool_object, deepseek_provider_core_tool_output_call_ids,
    deepseek_provider_core_top_logprobs_from_responses_request,
    deepseek_provider_core_user_id_from_responses_request, deepseek_provider_core_user_message,
    deepseek_provider_core_validate_function_name,
    deepseek_provider_core_validate_function_parameters,
    deepseek_provider_core_validate_reasoning_shape,
    deepseek_provider_core_validate_supported_input_item,
    deepseek_provider_core_validate_tool_choice_name,
    deepseek_provider_core_validate_tool_choice_shape,
    deepseek_provider_core_validate_tool_choice_target,
    deepseek_provider_core_validate_tools_shape,
    deepseek_provider_core_validate_web_search_options,
    deepseek_provider_core_validate_web_search_tool_context_size,
};
pub use errors::{
    ProviderErrorClass, ProviderErrorClassification, classify_provider_error,
    classify_provider_error_body,
};
pub use fallback::{
    provider_canonical_model, provider_gemini_retain_code_assist_models,
    provider_model_allows_session_memory, provider_model_fallback_chain,
    provider_model_from_request_body, provider_request_body_with_model,
};
pub use gemini_bridge::{
    GEMINI_PROVIDER_CORE_LIVE_AUDIO_RATE, GEMINI_PROVIDER_CORE_LOCAL_COMPACT_SUMMARY_PREFIX,
    GEMINI_PROVIDER_CORE_MAX_INLINE_RATE_LIMIT_RETRY_DELAY_MS, GeminiProviderCoreLiveAudioConfig,
    GeminiProviderCoreLiveAudioFormat, GeminiProviderCoreLiveAudioPayload,
    GeminiProviderCorePrecommitDecision, GeminiProviderCorePrecommitProbe,
    gemini_provider_core_append_media_parts_to_last_user_content,
    gemini_provider_core_apply_gemini3_tool_declaration_overrides,
    gemini_provider_core_blocked_tool_call_item, gemini_provider_core_body_has_terminal_quota,
    gemini_provider_core_bool_str, gemini_provider_core_bool_value,
    gemini_provider_core_buffered_responses_value, gemini_provider_core_builtin_tools_from_request,
    gemini_provider_core_chat_assistant_messages,
    gemini_provider_core_chat_assistant_tool_call_item, gemini_provider_core_chat_message_text,
    gemini_provider_core_citation_text, gemini_provider_core_collect_input_texts,
    gemini_provider_core_collect_media_parts, gemini_provider_core_collect_path_values,
    gemini_provider_core_collect_string_values, gemini_provider_core_compact_response_body,
    gemini_provider_core_content, gemini_provider_core_contextual_user_instruction_text,
    gemini_provider_core_conversation_requests_command_output_only,
    gemini_provider_core_custom_tool_input_from_arguments, gemini_provider_core_data_url_parts,
    gemini_provider_core_exact_output_generate_chunk, gemini_provider_core_exact_output_sse_stream,
    gemini_provider_core_finish_reason, gemini_provider_core_finish_reason_failure,
    gemini_provider_core_finish_reason_incomplete,
    gemini_provider_core_finish_reason_retryable_invalid,
    gemini_provider_core_forced_command_output, gemini_provider_core_function_call_part,
    gemini_provider_core_function_call_part_from_tool_call,
    gemini_provider_core_function_declaration_from_openai_tool,
    gemini_provider_core_function_response_content_part,
    gemini_provider_core_function_response_from_tool_message,
    gemini_provider_core_function_response_part, gemini_provider_core_function_tools_from_chat,
    gemini_provider_core_gemini3_tool_description,
    gemini_provider_core_generate_content_body_value,
    gemini_provider_core_generate_content_request,
    gemini_provider_core_generate_content_request_map,
    gemini_provider_core_generation_config_from_request, gemini_provider_core_google_quota_message,
    gemini_provider_core_harden_contents, gemini_provider_core_harden_tool_call_thought_signatures,
    gemini_provider_core_image_generation_call_item_from_part,
    gemini_provider_core_image_url_value, gemini_provider_core_import_contents_from_value,
    gemini_provider_core_internal_instruction_corpus,
    gemini_provider_core_internal_instruction_leak_text,
    gemini_provider_core_invalid_stream_retry_delay_ms,
    gemini_provider_core_is_contextual_user_fragment,
    gemini_provider_core_live_audio_config_from_value,
    gemini_provider_core_live_audio_rate_from_mime,
    gemini_provider_core_live_audio_stream_end_message,
    gemini_provider_core_live_binary_frame_error, gemini_provider_core_live_client_content_message,
    gemini_provider_core_live_conversation_item_deleted_event,
    gemini_provider_core_live_conversation_item_truncated_event,
    gemini_provider_core_live_decode_alaw, gemini_provider_core_live_decode_ulaw,
    gemini_provider_core_live_error_event, gemini_provider_core_live_field,
    gemini_provider_core_live_function_call_done_event,
    gemini_provider_core_live_function_declaration,
    gemini_provider_core_live_input_audio_cleared_event,
    gemini_provider_core_live_input_audio_payload,
    gemini_provider_core_live_input_audio_transcription_completed_event,
    gemini_provider_core_live_input_audio_transcription_delta_event,
    gemini_provider_core_live_legacy_session_audio_config,
    gemini_provider_core_live_output_audio_delta_event,
    gemini_provider_core_live_output_audio_transcript_delta_event,
    gemini_provider_core_live_output_audio_transcript_done_event,
    gemini_provider_core_live_output_text_delta_event,
    gemini_provider_core_live_output_text_done_event,
    gemini_provider_core_live_provider_stream_error,
    gemini_provider_core_live_realtime_audio_message,
    gemini_provider_core_live_response_cancelled_event,
    gemini_provider_core_live_response_created_event,
    gemini_provider_core_live_response_done_event, gemini_provider_core_live_server_turn_complete,
    gemini_provider_core_live_session_audio_config,
    gemini_provider_core_live_session_updated_event, gemini_provider_core_live_setup_message,
    gemini_provider_core_live_tool_response_message, gemini_provider_core_live_transcript_delta,
    gemini_provider_core_live_transcription_text,
    gemini_provider_core_live_unsupported_event_error, gemini_provider_core_local_compact_summary,
    gemini_provider_core_local_context_text_part,
    gemini_provider_core_mask_tool_response_for_history,
    gemini_provider_core_media_content_item_from_part,
    gemini_provider_core_media_part_from_content_object, gemini_provider_core_media_part_from_data,
    gemini_provider_core_media_part_from_uri_or_data_url, gemini_provider_core_mime_type_for_uri,
    gemini_provider_core_mime_type_is_text, gemini_provider_core_model_uses_gemini3_toolset,
    gemini_provider_core_native_request_body_with_project,
    gemini_provider_core_non_actionable_wait_or_poll_text,
    gemini_provider_core_normalize_tool_name, gemini_provider_core_normalized_error_body,
    gemini_provider_core_normalized_response_value,
    gemini_provider_core_parse_command_specific_tool,
    gemini_provider_core_precommit_decision_for_data_lines,
    gemini_provider_core_preserve_tool_call_signatures,
    gemini_provider_core_prompt_feedback_failure, gemini_provider_core_request_body,
    gemini_provider_core_request_body_without_tool,
    gemini_provider_core_response_bindings_from_body,
    gemini_provider_core_response_id_from_responses_value, gemini_provider_core_response_metadata,
    gemini_provider_core_response_retryable_quota,
    gemini_provider_core_response_terminal_without_history,
    gemini_provider_core_response_tool_call_added_item,
    gemini_provider_core_response_tool_call_item, gemini_provider_core_response_tool_call_raw_item,
    gemini_provider_core_responses_usage, gemini_provider_core_retry_delay_ms,
    gemini_provider_core_retry_delay_ms_from_body, gemini_provider_core_runtime_responses_value,
    gemini_provider_core_sanitize_function_schema,
    gemini_provider_core_sanitize_internal_instruction_leak_text,
    gemini_provider_core_semantic_compact_continuation_summary,
    gemini_provider_core_semantic_compact_instructions,
    gemini_provider_core_semantic_compact_request_body,
    gemini_provider_core_semantic_compact_summary, gemini_provider_core_session_checkpoint_value,
    gemini_provider_core_should_inline_rate_limit_retry,
    gemini_provider_core_should_rotate_after_quota_response, gemini_provider_core_simple_request,
    gemini_provider_core_simple_response, gemini_provider_core_skip_context_path_name,
    gemini_provider_core_stream_error, gemini_provider_core_structured_command_tool_response,
    gemini_provider_core_system_instruction_from_chat,
    gemini_provider_core_text_echoes_internal_instruction,
    gemini_provider_core_text_from_special_part, gemini_provider_core_text_part,
    gemini_provider_core_thought_signature, gemini_provider_core_tool_aliases,
    gemini_provider_core_tool_call_command_text,
    gemini_provider_core_tool_call_ids_from_responses_value,
    gemini_provider_core_tool_config_from_request, gemini_provider_core_tool_intent_without_call,
    gemini_provider_core_tool_is_mutating, gemini_provider_core_tool_output_call_ids_from_request,
    gemini_provider_core_tool_output_preview, gemini_provider_core_tool_response_output_string,
    gemini_provider_core_tools_from_requests, gemini_provider_core_truncate_to_bytes,
    gemini_provider_core_unsupported_tool_fallback_body,
    gemini_provider_core_unverified_success_claim, gemini_provider_core_visible_text_from_part,
    gemini_provider_core_web_search_call_from_grounding,
};
pub use models::{provider_model_catalog, provider_model_cost, provider_model_spec};
use replay_cases::provider_replay_case_count;
pub use replay_cases::{ProviderReplayCase, provider_replay_cases};
pub use surface::*;
pub(crate) use surface::{
    COPILOT_TEXT_ENDPOINTS, CORE_TEXT_ENDPOINTS, GEMINI_ENDPOINTS, KIRO_ENDPOINTS, OPENAI_ENDPOINTS,
};
pub use translator::{
    ProviderConformanceCase, ProviderConformanceExpectedErrorClass,
    ProviderConformanceExpectedLoss, ProviderConformanceOperation, ProviderParamSupport,
    ProviderTransformInput, ProviderTransformLoss, ProviderTransformResult, ProviderTranslator,
    ProviderUnsupportedReason, TransformOutcome, TransformStatus,
};
pub use translators::{
    DeepSeekProviderCoreStreamChatToolCall, DeepSeekProviderCoreStreamChoiceDelta,
    DeepSeekProviderCoreStreamChoiceMetadata, DeepSeekProviderCoreStreamChunkMetadata,
    DeepSeekProviderCoreStreamToolCallDelta, GeminiProviderCoreStreamChunkMetadata,
    GeminiProviderCoreStreamFunctionCallDelta, GeminiProviderCoreStreamToolCall,
    KiroProviderCoreRequestError, copilot_provider_core_request_body_with_canonical_model,
    copilot_provider_core_request_body_without_encrypted_content,
    copilot_provider_core_request_has_agent_input, copilot_provider_core_request_has_vision_input,
    copilot_provider_core_response_id_from_value, deepseek_provider_core_chat_stream_error,
    deepseek_provider_core_function_call_arguments_delta_event,
    deepseek_provider_core_output_item_added_event, deepseek_provider_core_output_item_done_event,
    deepseek_provider_core_output_text_delta_event,
    deepseek_provider_core_response_completed_event, deepseek_provider_core_response_created_event,
    deepseek_provider_core_stream_chat_assistant_message,
    deepseek_provider_core_stream_choice_delta, deepseek_provider_core_stream_choice_metadata,
    deepseek_provider_core_stream_chunk_metadata,
    deepseek_provider_core_stream_fallback_response_id,
    deepseek_provider_core_stream_fallback_tool_call_id,
    deepseek_provider_core_stream_first_choice,
    deepseek_provider_core_stream_function_call_arguments_delta_source,
    deepseek_provider_core_stream_output_text_item,
    deepseek_provider_core_stream_output_text_item_id,
    deepseek_provider_core_stream_response_id_from_chunk,
    deepseek_provider_core_stream_response_metadata, deepseek_provider_core_stream_response_value,
    deepseek_provider_core_stream_text_delta_source,
    deepseek_provider_core_stream_tool_call_added_item,
    deepseek_provider_core_stream_tool_call_delta, deepseek_provider_core_stream_tool_call_item,
    deepseek_provider_core_validate_stream_tool_call_arguments,
    deepseek_provider_core_validate_stream_tool_call_delta,
    gemini_provider_core_function_call_arguments_delta_event,
    gemini_provider_core_function_call_arguments_delta_event_with_thought_signature,
    gemini_provider_core_output_item_added_event, gemini_provider_core_output_item_done_event,
    gemini_provider_core_output_text_delta_event,
    gemini_provider_core_reasoning_summary_part_added_event,
    gemini_provider_core_reasoning_summary_text_delta_event,
    gemini_provider_core_response_completed_event, gemini_provider_core_response_created_event,
    gemini_provider_core_response_incomplete_event, gemini_provider_core_response_metadata_event,
    gemini_provider_core_stream_candidate_parts,
    gemini_provider_core_stream_chat_assistant_message, gemini_provider_core_stream_chunk_metadata,
    gemini_provider_core_stream_citation_item_id,
    gemini_provider_core_stream_completed_tool_call_arguments,
    gemini_provider_core_stream_completed_tool_call_item,
    gemini_provider_core_stream_fallback_response_id,
    gemini_provider_core_stream_fallback_tool_call_id,
    gemini_provider_core_stream_function_call_arguments_delta_source,
    gemini_provider_core_stream_function_call_delta, gemini_provider_core_stream_media_item_id,
    gemini_provider_core_stream_message_item, gemini_provider_core_stream_output_items,
    gemini_provider_core_stream_output_message_item,
    gemini_provider_core_stream_output_text_content,
    gemini_provider_core_stream_output_text_item_id,
    gemini_provider_core_stream_part_function_call,
    gemini_provider_core_stream_part_has_video_metadata,
    gemini_provider_core_stream_part_is_thought, gemini_provider_core_stream_part_text,
    gemini_provider_core_stream_reasoning_delta_source,
    gemini_provider_core_stream_response_id_from_chunk, gemini_provider_core_stream_response_value,
    gemini_provider_core_stream_should_emit_function_call_arguments_delta,
    gemini_provider_core_stream_text_delta_source, gemini_provider_core_stream_tool_call,
    gemini_provider_core_stream_tool_call_added_item,
    gemini_provider_core_stream_tool_call_arguments_value,
    gemini_provider_core_stream_tool_call_ids, kiro_provider_core_acp_assistant_output_message,
    kiro_provider_core_acp_chat_assistant_message, kiro_provider_core_acp_chat_tool_call_item,
    kiro_provider_core_acp_error_value, kiro_provider_core_acp_incomplete_details,
    kiro_provider_core_acp_incomplete_details_value, kiro_provider_core_acp_initialize_request,
    kiro_provider_core_acp_mark_failed_response, kiro_provider_core_acp_mark_incomplete_response,
    kiro_provider_core_acp_metadata, kiro_provider_core_acp_model_value,
    kiro_provider_core_acp_plan_entry, kiro_provider_core_acp_response_value,
    kiro_provider_core_acp_responses_tool_call_item, kiro_provider_core_acp_session_info,
    kiro_provider_core_acp_session_new_request, kiro_provider_core_acp_session_prompt_request,
    kiro_provider_core_acp_stop_reason, kiro_provider_core_acp_usage_update_json,
    kiro_provider_core_anthropic_message_value_from_response,
    kiro_provider_core_apply_response_runtime_metadata, kiro_provider_core_chat_completion_chunk,
    kiro_provider_core_chat_completion_empty_delta,
    kiro_provider_core_chat_completion_finish_reason,
    kiro_provider_core_chat_completion_finish_reason_from_response,
    kiro_provider_core_chat_completion_role_delta, kiro_provider_core_chat_completion_text_delta,
    kiro_provider_core_chat_completion_tool_call_delta,
    kiro_provider_core_chat_completion_value_from_response,
    kiro_provider_core_chat_completions_request_body,
    kiro_provider_core_compact_summary_from_response,
    kiro_provider_core_invalid_request_error_value, kiro_provider_core_model_list_value,
    kiro_provider_core_model_value_or_not_found, kiro_provider_core_output_item_added_event,
    kiro_provider_core_output_item_done_event, kiro_provider_core_output_text_delta_event,
    kiro_provider_core_prompt_from_chat_messages, kiro_provider_core_response_completed_event,
    kiro_provider_core_response_created_event, kiro_provider_core_response_has_tool_calls,
    kiro_provider_core_responses_items_from_chat_message,
    kiro_provider_core_semantic_compact_instructions,
    kiro_provider_core_semantic_compact_request_body, kiro_provider_core_stream_content_text,
    kiro_provider_core_stream_tool_arguments, kiro_provider_core_stream_tool_call_item,
    kiro_provider_core_tool_call_arguments_delta_chat_value,
    kiro_provider_core_tool_choice_from_legacy_chat_function_call,
    kiro_provider_core_tool_from_legacy_chat_function,
    kiro_provider_core_unsupported_path_error_value, provider_conformance_cases,
    provider_translator,
};
pub use usage::{
    ProviderTokenUsage, calculate_cost_microusd, estimate_request_input_tokens,
    estimate_text_tokens, extract_usage_tokens, microusd_to_usd,
};
