sonar.sources=src,crates
sonar.inclusions=src/**/*.rs,crates/**/*.rs
sonar.exclusions=**/test/**,**/tests/**,**/benches/**,**/examples/**,**/fuzz/**,**/generated/**,**/vendor/**,**/target/**,**/*_test.rs,**/*_tests.rs,**/test_*.rs
sonar.rust.clippy.enable=false
sonar.rust.clippyReport.reportPaths=sonar-clippy.json
sonar.qualitygate.wait=true
