use std::collections::BTreeMap;
use std::path::PathBuf;

use serde::Serialize;

#[derive(Debug, Clone, Default)]
pub(crate) struct RuntimeDoctorSummary {
    pub(crate) log_path: Option<PathBuf>,
    pub(crate) pointer_exists: bool,
    pub(crate) log_exists: bool,
    pub(crate) line_count: usize,
    pub(crate) marker_counts: BTreeMap<&'static str, usize>,
    pub(crate) last_marker_line: Option<String>,
    pub(crate) marker_last_fields: BTreeMap<&'static str, BTreeMap<String, String>>,
    pub(crate) facet_counts: BTreeMap<String, BTreeMap<String, usize>>,
    pub(crate) previous_response_not_found_by_route: BTreeMap<String, usize>,
    pub(crate) previous_response_not_found_by_transport: BTreeMap<String, usize>,
    pub(crate) chain_retried_owner_by_reason: BTreeMap<String, usize>,
    pub(crate) chain_dead_upstream_confirmed_by_reason: BTreeMap<String, usize>,
    pub(crate) stale_continuation_by_reason: BTreeMap<String, usize>,
    pub(crate) latest_chain_event: Option<String>,
    pub(crate) latest_stale_continuation_reason: Option<String>,
    pub(crate) first_timestamp: Option<String>,
    pub(crate) last_timestamp: Option<String>,
    pub(crate) compat_warning_count: usize,
    pub(crate) top_client_family: Option<String>,
    pub(crate) top_client: Option<String>,
    pub(crate) top_tool_surface: Option<String>,
    pub(crate) top_compat_warning: Option<String>,
    pub(crate) selection_pressure: String,
    pub(crate) transport_pressure: String,
    pub(crate) persistence_pressure: String,
    pub(crate) quota_freshness_pressure: String,
    pub(crate) startup_audit_pressure: String,
    pub(crate) persisted_retry_backoffs: usize,
    pub(crate) persisted_transport_backoffs: usize,
    pub(crate) persisted_route_circuits: usize,
    pub(crate) persisted_usage_snapshots: usize,
    pub(crate) persisted_response_bindings: usize,
    pub(crate) persisted_session_bindings: usize,
    pub(crate) persisted_turn_state_bindings: usize,
    pub(crate) persisted_session_id_bindings: usize,
    pub(crate) persisted_verified_continuations: usize,
    pub(crate) persisted_warm_continuations: usize,
    pub(crate) persisted_suspect_continuations: usize,
    pub(crate) persisted_dead_continuations: usize,
    pub(crate) persisted_continuation_journal_response_bindings: usize,
    pub(crate) persisted_continuation_journal_session_bindings: usize,
    pub(crate) persisted_continuation_journal_turn_state_bindings: usize,
    pub(crate) persisted_continuation_journal_session_id_bindings: usize,
    pub(crate) persisted_turn_state_coverage_percent: Option<u8>,
    pub(crate) state_save_queue_backlog: Option<usize>,
    pub(crate) state_save_lag_ms: Option<u64>,
    pub(crate) continuation_journal_save_backlog: Option<usize>,
    pub(crate) continuation_journal_save_lag_ms: Option<u64>,
    pub(crate) profile_probe_refresh_backlog: Option<usize>,
    pub(crate) profile_probe_refresh_lag_ms: Option<u64>,
    pub(crate) continuation_journal_saved_at: Option<i64>,
    pub(crate) suspect_continuation_bindings: Vec<String>,
    pub(crate) failure_class_counts: BTreeMap<String, usize>,
    pub(crate) stale_persisted_usage_snapshots: usize,
    pub(crate) recovered_state_file: bool,
    pub(crate) recovered_scores_file: bool,
    pub(crate) recovered_usage_snapshots_file: bool,
    pub(crate) recovered_backoffs_file: bool,
    pub(crate) recovered_continuations_file: bool,
    pub(crate) recovered_continuation_journal_file: bool,
    pub(crate) last_good_backups_present: usize,
    pub(crate) degraded_routes: Vec<String>,
    pub(crate) orphan_managed_dirs: Vec<String>,
    pub(crate) prodex_binary_identities: Vec<String>,
    pub(crate) runtime_broker_identities: Vec<String>,
    pub(crate) prodex_binary_mismatch: bool,
    pub(crate) runtime_broker_mismatch: bool,
    pub(crate) profiles: Vec<RuntimeDoctorProfileSummary>,
    pub(crate) diagnosis: String,
}

#[derive(Debug, Clone, Default, Serialize)]
pub(crate) struct RuntimeDoctorProfileSummary {
    pub(crate) profile: String,
    pub(crate) quota_freshness: String,
    pub(crate) quota_age_seconds: i64,
    pub(crate) retry_backoff_until: Option<i64>,
    pub(crate) transport_backoff_until: Option<i64>,
    pub(crate) routes: Vec<RuntimeDoctorRouteSummary>,
}

#[derive(Debug, Clone, Default, Serialize)]
pub(crate) struct RuntimeDoctorRouteSummary {
    pub(crate) route: String,
    pub(crate) circuit_state: String,
    pub(crate) circuit_until: Option<i64>,
    pub(crate) transport_backoff_until: Option<i64>,
    pub(crate) health_score: u32,
    pub(crate) bad_pairing_score: u32,
    pub(crate) performance_score: u32,
    pub(crate) quota_band: String,
    pub(crate) five_hour_status: String,
    pub(crate) weekly_status: String,
}
