//! Copilot provider model catalog data.

use super::super::model;
use super::super::{
    COPILOT_ANTHROPIC_CONTEXT_WINDOW_TOKENS, COPILOT_EXTENDED_CONTEXT_WINDOW_TOKENS,
    COPILOT_GEMINI_CONTEXT_WINDOW_TOKENS, COPILOT_OPENAI_CONTEXT_WINDOW_TOKENS,
};
use crate::COPILOT_TEXT_ENDPOINTS;
use crate::{ProviderId, ProviderModelSpec};

pub(in crate::models) const MODELS: &[ProviderModelSpec] = &[
    model!(
        ProviderId::Copilot,
        "github-copilot",
        "auto",
        "Copilot Auto",
        "GitHub Copilot alias routed through provider fallback.",
        Some(COPILOT_EXTENDED_CONTEXT_WINDOW_TOKENS),
        None,
        None,
        COPILOT_TEXT_ENDPOINTS,
        ["default"]
    ),
    model!(
        ProviderId::Copilot,
        "github-copilot",
        "codex",
        "Copilot Codex",
        "GitHub Copilot Codex alias routed through provider fallback.",
        Some(COPILOT_EXTENDED_CONTEXT_WINDOW_TOKENS),
        None,
        None,
        COPILOT_TEXT_ENDPOINTS,
        ["pro"]
    ),
    model!(
        ProviderId::Copilot,
        "github-copilot",
        "gpt-5.3-codex",
        "GPT-5.3 Codex",
        "GitHub Copilot model exposed through Prodex.",
        Some(COPILOT_EXTENDED_CONTEXT_WINDOW_TOKENS),
        None,
        None,
        COPILOT_TEXT_ENDPOINTS,
        []
    ),
    model!(
        ProviderId::Copilot,
        "github-copilot",
        "gpt-5.5",
        "GPT-5.5",
        "GitHub Copilot model exposed through Prodex.",
        Some(COPILOT_EXTENDED_CONTEXT_WINDOW_TOKENS),
        None,
        None,
        COPILOT_TEXT_ENDPOINTS,
        ["best"]
    ),
    model!(
        ProviderId::Copilot,
        "github-copilot",
        "gpt-5.4",
        "GPT-5.4",
        "GitHub Copilot model exposed through Prodex.",
        Some(COPILOT_EXTENDED_CONTEXT_WINDOW_TOKENS),
        None,
        None,
        COPILOT_TEXT_ENDPOINTS,
        []
    ),
    model!(
        ProviderId::Copilot,
        "github-copilot",
        "gpt-5.4-mini",
        "GPT-5.4 Mini",
        "GitHub Copilot model exposed through Prodex.",
        Some(COPILOT_OPENAI_CONTEXT_WINDOW_TOKENS),
        None,
        None,
        COPILOT_TEXT_ENDPOINTS,
        ["mini"]
    ),
    model!(
        ProviderId::Copilot,
        "github-copilot",
        "gpt-5.4-nano",
        "GPT-5.4 Nano",
        "GitHub Copilot model exposed through Prodex.",
        Some(COPILOT_OPENAI_CONTEXT_WINDOW_TOKENS),
        None,
        None,
        COPILOT_TEXT_ENDPOINTS,
        ["nano"]
    ),
    model!(
        ProviderId::Copilot,
        "github-copilot",
        "gpt-5-mini",
        "GPT-5 Mini",
        "GitHub Copilot model exposed through Prodex.",
        Some(COPILOT_OPENAI_CONTEXT_WINDOW_TOKENS),
        None,
        None,
        COPILOT_TEXT_ENDPOINTS,
        []
    ),
    model!(
        ProviderId::Copilot,
        "github-copilot",
        "claude-sonnet-4-6",
        "Claude Sonnet 4.6",
        "GitHub Copilot model exposed through Prodex.",
        Some(COPILOT_EXTENDED_CONTEXT_WINDOW_TOKENS),
        None,
        None,
        COPILOT_TEXT_ENDPOINTS,
        ["claude", "sonnet"]
    ),
    model!(
        ProviderId::Copilot,
        "github-copilot",
        "claude-opus-4-8",
        "Claude Opus 4.8",
        "GitHub Copilot model exposed through Prodex.",
        Some(COPILOT_EXTENDED_CONTEXT_WINDOW_TOKENS),
        None,
        None,
        COPILOT_TEXT_ENDPOINTS,
        ["opus"]
    ),
    model!(
        ProviderId::Copilot,
        "github-copilot",
        "claude-opus-4-7",
        "Claude Opus 4.7",
        "GitHub Copilot model exposed through Prodex.",
        Some(COPILOT_EXTENDED_CONTEXT_WINDOW_TOKENS),
        None,
        None,
        COPILOT_TEXT_ENDPOINTS,
        []
    ),
    model!(
        ProviderId::Copilot,
        "github-copilot",
        "claude-opus-4-6-fast",
        "Claude Opus 4.6 Fast",
        "GitHub Copilot model exposed through Prodex.",
        Some(COPILOT_EXTENDED_CONTEXT_WINDOW_TOKENS),
        None,
        None,
        COPILOT_TEXT_ENDPOINTS,
        []
    ),
    model!(
        ProviderId::Copilot,
        "github-copilot",
        "claude-opus-4-6",
        "Claude Opus 4.6",
        "GitHub Copilot model exposed through Prodex.",
        Some(COPILOT_EXTENDED_CONTEXT_WINDOW_TOKENS),
        None,
        None,
        COPILOT_TEXT_ENDPOINTS,
        []
    ),
    model!(
        ProviderId::Copilot,
        "github-copilot",
        "claude-opus-4-5",
        "Claude Opus 4.5",
        "GitHub Copilot model exposed through Prodex.",
        Some(COPILOT_ANTHROPIC_CONTEXT_WINDOW_TOKENS),
        None,
        None,
        COPILOT_TEXT_ENDPOINTS,
        []
    ),
    model!(
        ProviderId::Copilot,
        "github-copilot",
        "claude-fable-5",
        "Claude Fable 5",
        "GitHub Copilot model exposed through Prodex.",
        Some(COPILOT_EXTENDED_CONTEXT_WINDOW_TOKENS),
        None,
        None,
        COPILOT_TEXT_ENDPOINTS,
        []
    ),
    model!(
        ProviderId::Copilot,
        "github-copilot",
        "claude-sonnet-4-5",
        "Claude Sonnet 4.5",
        "GitHub Copilot model exposed through Prodex.",
        Some(COPILOT_ANTHROPIC_CONTEXT_WINDOW_TOKENS),
        None,
        None,
        COPILOT_TEXT_ENDPOINTS,
        []
    ),
    model!(
        ProviderId::Copilot,
        "github-copilot",
        "claude-haiku-4-5",
        "Claude Haiku 4.5",
        "GitHub Copilot model exposed through Prodex.",
        Some(COPILOT_ANTHROPIC_CONTEXT_WINDOW_TOKENS),
        None,
        None,
        COPILOT_TEXT_ENDPOINTS,
        ["haiku"]
    ),
    model!(
        ProviderId::Copilot,
        "github-copilot",
        "gemini-3.1-pro-preview",
        "Gemini 3.1 Pro Preview",
        "GitHub Copilot model exposed through Prodex.",
        Some(COPILOT_GEMINI_CONTEXT_WINDOW_TOKENS),
        None,
        None,
        COPILOT_TEXT_ENDPOINTS,
        ["gemini"]
    ),
    model!(
        ProviderId::Copilot,
        "github-copilot",
        "gemini-2.5-pro",
        "Gemini 2.5 Pro",
        "GitHub Copilot model exposed through Prodex.",
        Some(COPILOT_GEMINI_CONTEXT_WINDOW_TOKENS),
        None,
        None,
        COPILOT_TEXT_ENDPOINTS,
        []
    ),
    model!(
        ProviderId::Copilot,
        "github-copilot",
        "gemini-3-flash",
        "Gemini 3 Flash",
        "GitHub Copilot model exposed through Prodex.",
        Some(COPILOT_GEMINI_CONTEXT_WINDOW_TOKENS),
        None,
        None,
        COPILOT_TEXT_ENDPOINTS,
        ["flash"]
    ),
    model!(
        ProviderId::Copilot,
        "github-copilot",
        "gemini-3.5-flash",
        "Gemini 3.5 Flash",
        "GitHub Copilot model exposed through Prodex.",
        Some(COPILOT_GEMINI_CONTEXT_WINDOW_TOKENS),
        None,
        None,
        COPILOT_TEXT_ENDPOINTS,
        []
    ),
    model!(
        ProviderId::Copilot,
        "github-copilot",
        "mai-code-1-flash",
        "MAI-Code-1-Flash",
        "GitHub Copilot model exposed through Prodex.",
        Some(COPILOT_OPENAI_CONTEXT_WINDOW_TOKENS),
        None,
        None,
        COPILOT_TEXT_ENDPOINTS,
        []
    ),
    model!(
        ProviderId::Copilot,
        "github-copilot",
        "raptor-mini",
        "Raptor Mini",
        "GitHub Copilot model exposed through Prodex.",
        Some(COPILOT_OPENAI_CONTEXT_WINDOW_TOKENS),
        None,
        None,
        COPILOT_TEXT_ENDPOINTS,
        []
    ),
    model!(
        ProviderId::Copilot,
        "github-copilot",
        "gpt-5.1-codex",
        "GPT-5.1 Codex",
        "Legacy GitHub Copilot model kept for compatibility.",
        Some(COPILOT_OPENAI_CONTEXT_WINDOW_TOKENS),
        None,
        None,
        COPILOT_TEXT_ENDPOINTS,
        []
    ),
    model!(
        ProviderId::Copilot,
        "github-copilot",
        "gpt-4o",
        "GPT-4o",
        "Legacy GitHub Copilot model kept as a safe fallback.",
        Some(COPILOT_OPENAI_CONTEXT_WINDOW_TOKENS),
        None,
        None,
        COPILOT_TEXT_ENDPOINTS,
        []
    ),
];
