[package]
name = "prodex-runtime-launch"
version.workspace = true
edition.workspace = true
description = "Runtime launch planning primitives for prodex"
license.workspace = true
repository.workspace = true

[lib]
name = "prodex_runtime_launch"
path = "src/lib.rs"

[features]
default = []
mojo = ["dep:prodex_mojo_core", "prodex_mojo_core/mojo-runtime"]

[dependencies]
prodex_mojo_core = { workspace = true, optional = true }
anyhow = { workspace = true }
codex_config = { workspace = true }
prodex_quota = { workspace = true }
prodex_shared_types = { workspace = true }
prodex_state = { workspace = true }
prodex_core = { workspace = true }
redaction = { workspace = true }
reqwest = { workspace = true }
runtime_proxy_crate = { workspace = true }
terminal_ui = { workspace = true }

[lints]
workspace = true
