[package]
name = "prodex-runtime-policy"
version.workspace = true
edition.workspace = true
description = "Runtime policy parsing and validation for prodex"
license.workspace = true
repository.workspace = true

[lib]
name = "prodex_runtime_policy"
path = "src/lib.rs"

[features]
default = []
mojo = []

[dependencies]
anyhow = { workspace = true }
prodex_core = { workspace = true }
prodex_mojo_core = { workspace = true, features = ["mojo-runtime", "mojo-rich"] }
secret_store = { workspace = true }
serde = { workspace = true }
toml = { workspace = true }

[lints]
workspace = true
