// Adapted from OpenCodex's browser control-plane interaction model.
// See THIRD_PARTY_NOTICES.md for the upstream MIT notice.
pub(crate) const DASHBOARD_HTML: &str = r##"<!doctype html>
<html lang="en" data-theme="system">
<head>
<meta charset="utf-8">
<meta name="viewport" content="width=device-width,initial-scale=1">
<meta name="color-scheme" content="light dark">
<link rel="icon" href="data:image/svg+xml,%3Csvg xmlns='http://www.w3.org/2000/svg' viewBox='0 0 32 32'%3E%3Crect width='32' height='32' rx='9' fill='%23171714'/%3E%3Ctext x='16' y='22' text-anchor='middle' font-family='sans-serif' font-size='18' font-weight='700' fill='white'%3EP%3C/text%3E%3C/svg%3E">
<title>Prodex Control Center</title>
<style>
:root{color-scheme:light;--bg:#f5f5f2;--surface:#fff;--surface-2:#f9f9f7;--surface-3:#efefeb;--text:#171714;--muted:#70706a;--line:#deded8;--line-strong:#c8c8c0;--accent:#0e766e;--accent-strong:#095f59;--accent-soft:#e1f3f0;--good:#147d64;--warn:#a56408;--bad:#bc3d3d;--shadow:0 14px 40px rgba(27,27,22,.08);--rail:244px}
:root[data-theme="dark"]{color-scheme:dark;--bg:#10110f;--surface:#181916;--surface-2:#1e201c;--surface-3:#292b26;--text:#f1f1eb;--muted:#a2a39b;--line:#30322d;--line-strong:#464942;--accent:#58cbbd;--accent-strong:#7cdbcf;--accent-soft:#183b36;--good:#64d2b4;--warn:#e6ad55;--bad:#ef7e7e;--shadow:0 18px 50px rgba(0,0,0,.28)}
@media(prefers-color-scheme:dark){:root:not([data-theme="light"]){color-scheme:dark;--bg:#10110f;--surface:#181916;--surface-2:#1e201c;--surface-3:#292b26;--text:#f1f1eb;--muted:#a2a39b;--line:#30322d;--line-strong:#464942;--accent:#58cbbd;--accent-strong:#7cdbcf;--accent-soft:#183b36;--good:#64d2b4;--warn:#e6ad55;--bad:#ef7e7e;--shadow:0 18px 50px rgba(0,0,0,.28)}}
*{box-sizing:border-box}html,body{margin:0;min-height:100%;background:var(--bg);color:var(--text);font:14px/1.5 Inter,ui-sans-serif,system-ui,-apple-system,BlinkMacSystemFont,"Segoe UI",sans-serif}button,input,select{font:inherit}button{color:inherit}.app{min-height:100vh}.rail{position:fixed;inset:0 auto 0 0;width:var(--rail);padding:18px 14px;display:flex;flex-direction:column;background:color-mix(in srgb,var(--surface) 90%,transparent);border-right:1px solid var(--line);backdrop-filter:blur(18px);z-index:30}.brand{height:48px;display:flex;align-items:center;gap:11px;padding:0 10px;margin-bottom:15px}.brand-mark{width:34px;height:34px;border-radius:10px;display:grid;place-items:center;background:var(--text);color:var(--surface);font-weight:800;letter-spacing:-.04em}.brand-name{font-weight:760;font-size:16px;letter-spacing:-.02em}.brand-meta{font-size:11px;color:var(--muted)}.nav-label{padding:8px 11px 6px;color:var(--muted);font-size:10px;text-transform:uppercase;letter-spacing:.12em;font-weight:700}.nav{display:grid;gap:3px}.nav-item{width:100%;height:40px;padding:0 10px;border:0;border-radius:9px;background:transparent;display:flex;align-items:center;gap:10px;text-align:left;cursor:pointer;color:var(--muted);transition:background .16s,color .16s}.nav-item:hover{background:var(--surface-3);color:var(--text)}.nav-item[aria-current="page"]{background:var(--accent-soft);color:var(--accent-strong);font-weight:650}.nav-icon{width:22px;height:22px;display:grid;place-items:center;font-size:15px}.rail-footer{margin-top:auto;padding:12px 10px 2px;border-top:1px solid var(--line);display:grid;gap:6px}.server-state{display:flex;align-items:center;gap:8px;font-size:12px;color:var(--muted)}.notice-link{font-size:10px;color:var(--muted);text-decoration:none}.notice-link:hover{color:var(--text)}.state-dot{width:7px;height:7px;border-radius:50%;background:var(--muted)}.state-dot.ok{background:var(--good);box-shadow:0 0 0 4px color-mix(in srgb,var(--good) 12%,transparent)}.state-dot.busy{background:var(--warn);animation:pulse 1.1s infinite}.state-dot.bad{background:var(--bad)}@keyframes pulse{50%{opacity:.35}}
.workspace{min-height:100vh;margin-left:var(--rail)}.topbar{height:72px;padding:0 28px;display:flex;align-items:center;justify-content:space-between;gap:18px;border-bottom:1px solid var(--line);background:color-mix(in srgb,var(--bg) 87%,transparent);backdrop-filter:blur(14px);position:sticky;top:0;z-index:20}.heading h1{margin:0;font-size:19px;line-height:1.25;letter-spacing:-.025em}.heading p{margin:3px 0 0;color:var(--muted);font-size:12px}.top-actions{display:flex;align-items:center;gap:8px}.icon-button,.button{min-height:36px;border:1px solid var(--line);border-radius:9px;background:var(--surface);cursor:pointer;display:inline-flex;align-items:center;justify-content:center;gap:7px;transition:border-color .15s,background .15s,transform .08s}.icon-button{width:36px;padding:0}.button{padding:7px 12px;font-weight:620}.button:hover,.icon-button:hover{border-color:var(--line-strong);background:var(--surface-2)}.button:active,.icon-button:active{transform:translateY(1px)}.button.primary{background:var(--text);border-color:var(--text);color:var(--surface)}.button.danger{color:var(--bad)}.button:disabled,.icon-button:disabled{opacity:.5;cursor:not-allowed}.menu-button{display:none}.content{max-width:1460px;margin:0 auto;padding:26px 30px 60px}.page[hidden]{display:none}.page-head{display:flex;align-items:flex-end;justify-content:space-between;gap:18px;margin-bottom:18px}.page-head h2{font-size:24px;margin:0;letter-spacing:-.035em}.page-head p{margin:5px 0 0;color:var(--muted);max-width:700px}.eyebrow{font-size:10px;text-transform:uppercase;letter-spacing:.13em;font-weight:750;color:var(--muted);margin-bottom:4px}
.stats{display:grid;grid-template-columns:repeat(4,minmax(0,1fr));gap:12px;margin-bottom:18px}.stat,.card{border:1px solid var(--line);background:var(--surface);border-radius:13px}.stat{padding:16px 17px;min-height:100px;display:flex;flex-direction:column;justify-content:space-between}.stat-label{color:var(--muted);font-size:12px}.stat-value{font-size:29px;line-height:1;font-weight:760;letter-spacing:-.045em}.stat-foot{color:var(--muted);font-size:11px}.grid-2{display:grid;grid-template-columns:minmax(0,1.25fr) minmax(300px,.75fr);gap:14px}.card{overflow:hidden}.card-head{min-height:52px;padding:13px 16px;display:flex;align-items:center;justify-content:space-between;gap:12px;border-bottom:1px solid var(--line)}.card-title{font-weight:700;letter-spacing:-.01em}.card-subtitle{font-size:11px;color:var(--muted);margin-top:1px}.card-body{padding:16px}.stack{display:grid;gap:12px}.empty{padding:28px 16px;text-align:center;color:var(--muted)}.callout{padding:14px;border:1px solid color-mix(in srgb,var(--accent) 35%,var(--line));border-radius:11px;background:var(--accent-soft)}.callout strong{display:block;margin-bottom:3px}.active-profile{display:flex;align-items:center;gap:13px}.avatar{width:40px;height:40px;border-radius:11px;display:grid;place-items:center;background:var(--accent-soft);color:var(--accent-strong);font-weight:800;text-transform:uppercase}.grow{min-width:0;flex:1}.truncate{white-space:nowrap;overflow:hidden;text-overflow:ellipsis}.muted{color:var(--muted)}.small{font-size:12px}.tiny{font-size:11px}.good{color:var(--good)}.warn{color:var(--warn)}.bad{color:var(--bad)}.badge{display:inline-flex;align-items:center;min-height:23px;padding:2px 8px;border:1px solid var(--line);border-radius:999px;background:var(--surface-2);font-size:11px;white-space:nowrap}.badge.good{border-color:color-mix(in srgb,var(--good) 35%,var(--line));background:color-mix(in srgb,var(--good) 10%,var(--surface))}.badge.warn{border-color:color-mix(in srgb,var(--warn) 35%,var(--line));background:color-mix(in srgb,var(--warn) 10%,var(--surface))}.badge.bad{border-color:color-mix(in srgb,var(--bad) 35%,var(--line));background:color-mix(in srgb,var(--bad) 10%,var(--surface))}.badge-row{display:flex;gap:6px;flex-wrap:wrap}.provider-list{display:grid;gap:8px}.provider-mini{padding:10px 11px;border:1px solid var(--line);border-radius:10px;display:flex;align-items:center;gap:10px}.provider-dot{width:9px;height:9px;border-radius:50%;background:var(--line-strong)}.provider-dot.active{background:var(--good)}
.toolbar{display:flex;align-items:center;gap:8px;flex-wrap:wrap}.field{min-height:37px;border:1px solid var(--line);background:var(--surface);color:var(--text);border-radius:9px;padding:7px 10px;outline:none}.field:focus{border-color:var(--accent);box-shadow:0 0 0 3px color-mix(in srgb,var(--accent) 14%,transparent)}select.field{cursor:pointer}.search{min-width:240px}.form-row{display:flex;gap:8px;flex-wrap:wrap}.form-row .field{flex:1;min-width:190px}.command-grid{display:grid;grid-template-columns:repeat(2,minmax(0,1fr));gap:9px}.command-card{border:1px solid var(--line);background:var(--surface-2);border-radius:10px;padding:11px}.command-top{display:flex;align-items:center;justify-content:space-between;gap:8px;margin-bottom:7px}.command-label{font-size:10px;text-transform:uppercase;letter-spacing:.09em;color:var(--muted);font-weight:700}.copy-button{border:0;background:transparent;color:var(--muted);cursor:pointer;font-size:11px;padding:2px 4px}.copy-button:hover{color:var(--text)}code,.mono{font:12px/1.5 ui-monospace,SFMono-Regular,Consolas,"Liberation Mono",monospace}.command-code{display:block;white-space:pre-wrap;overflow-wrap:anywhere;color:var(--text)}
.table-wrap{overflow:auto}.table{width:100%;border-collapse:collapse}.table th,.table td{text-align:left;padding:11px 13px;border-bottom:1px solid var(--line);vertical-align:top}.table th{position:sticky;top:0;background:var(--surface-2);z-index:1;color:var(--muted);font-size:10px;text-transform:uppercase;letter-spacing:.08em;font-weight:750;white-space:nowrap}.table tr:last-child td{border-bottom:0}.table tbody tr{transition:background .12s}.table tbody tr:hover{background:var(--surface-2)}.table .command-cell{max-width:360px;font:11px/1.45 ui-monospace,SFMono-Regular,Consolas,monospace;overflow-wrap:anywhere}.row-actions{display:flex;gap:6px;justify-content:flex-end}.model-name{font-weight:650}.model-id{color:var(--muted);font:11px/1.4 ui-monospace,SFMono-Regular,Consolas,monospace;margin-top:2px}.provider-detail{display:grid;grid-template-columns:minmax(220px,.65fr) minmax(0,1.35fr);gap:14px}.provider-summary{padding:18px;border:1px solid var(--line);border-radius:12px;background:var(--surface-2)}.provider-summary h3{font-size:20px;margin:0 0 5px}.provider-summary p{color:var(--muted);margin:0 0 14px}.quota-window{display:grid;gap:5px;min-width:150px}.quota-meta{display:flex;justify-content:space-between;gap:10px;font-size:11px;color:var(--muted)}.quota-track{height:6px;border-radius:999px;background:var(--surface-3);overflow:hidden}.quota-fill{height:100%;border-radius:inherit;background:var(--good)}.quota-fill.warn{background:var(--warn)}.quota-fill.bad{background:var(--bad)}
.log-toolbar{padding:12px 14px;border-bottom:1px solid var(--line)}.log-path{font:11px/1.4 ui-monospace,SFMono-Regular,Consolas,monospace;color:var(--muted);overflow-wrap:anywhere}.log-list{height:min(62vh,700px);overflow:auto;background:#11130f;color:#d8ddd3;padding:10px 0;font:11px/1.55 ui-monospace,SFMono-Regular,Consolas,monospace}.log-line{display:grid;grid-template-columns:46px minmax(0,1fr);gap:10px;padding:2px 13px;border-left:2px solid transparent}.log-line:hover{background:#1c2019}.log-line.warn{color:#f1c879;border-left-color:#c58a2d}.log-line.bad{color:#f09b9b;border-left-color:#d05959}.log-number{color:#70776c;text-align:right;user-select:none}.runtime-grid{display:grid;grid-template-columns:repeat(2,minmax(0,1fr));gap:14px}.detail-list{display:grid;gap:0}.detail-row{display:grid;grid-template-columns:150px minmax(0,1fr);gap:12px;padding:10px 0;border-bottom:1px solid var(--line)}.detail-row:last-child{border-bottom:0}.detail-key{color:var(--muted);font-size:12px}.detail-value{overflow-wrap:anywhere}.toast{position:fixed;right:22px;bottom:22px;z-index:80;max-width:min(380px,calc(100vw - 32px));padding:11px 14px;border-radius:10px;background:var(--text);color:var(--surface);box-shadow:var(--shadow);opacity:0;transform:translateY(8px);pointer-events:none;transition:opacity .16s,transform .16s}.toast.show{opacity:1;transform:none}.backdrop{display:none}
@media(max-width:1050px){.stats{grid-template-columns:repeat(2,minmax(0,1fr))}.grid-2,.provider-detail{grid-template-columns:1fr}.hide-md{display:none}}
@media(max-width:760px){:root{--rail:232px}.rail{transform:translateX(-102%);transition:transform .2s;box-shadow:var(--shadow)}.rail.open{transform:none}.workspace{margin-left:0}.backdrop{display:block;position:fixed;inset:0;background:rgba(0,0,0,.38);z-index:25;opacity:0;pointer-events:none;transition:opacity .2s}.backdrop.open{opacity:1;pointer-events:auto}.menu-button{display:inline-flex}.topbar{height:64px;padding:0 15px}.heading p{display:none}.content{padding:20px 15px 46px}.page-head{align-items:flex-start;flex-direction:column}.command-grid,.runtime-grid{grid-template-columns:1fr}.hide-sm{display:none}.search{min-width:0;width:100%}}
@media(max-width:480px){.stats{grid-template-columns:1fr 1fr;gap:8px}.stat{min-height:88px;padding:13px}.stat-value{font-size:25px}.top-actions .button span{display:none}.content{padding-left:11px;padding-right:11px}.card-head,.card-body{padding-left:13px;padding-right:13px}.table th,.table td{padding:9px}.row-actions{flex-direction:column}.detail-row{grid-template-columns:1fr;gap:3px}}
@media(prefers-reduced-motion:reduce){*,*:before,*:after{scroll-behavior:auto!important;transition:none!important;animation:none!important}}
</style>
</head>
<body>
<div class="app">
  <aside class="rail" id="rail">
    <div class="brand"><div class="brand-mark">P</div><div><div class="brand-name">Prodex</div><div class="brand-meta">Control Center</div></div></div>
    <div class="nav-label">Workspace</div>
    <nav class="nav" aria-label="Dashboard pages">
      <button class="nav-item" data-route="overview"><span class="nav-icon">⌂</span><span>Overview</span></button>
      <button class="nav-item" data-route="providers"><span class="nav-icon">◫</span><span>Providers</span></button>
      <button class="nav-item" data-route="models"><span class="nav-icon">◇</span><span>Models</span></button>
      <button class="nav-item" data-route="usage"><span class="nav-icon">◔</span><span>Usage</span></button>
      <button class="nav-item" data-route="accounts"><span class="nav-icon">◎</span><span>Accounts</span></button>
      <button class="nav-item" data-route="logs"><span class="nav-icon">≡</span><span>Runtime logs</span></button>
      <button class="nav-item" data-route="runtime"><span class="nav-icon">⚙</span><span>Runtime</span></button>
    </nav>
    <div class="rail-footer">
      <div class="server-state"><span class="state-dot busy" id="serverDot"></span><span id="serverState">Connecting</span></div>
      <div class="tiny muted" id="lastUpdated">Waiting for first snapshot</div>
      <a class="notice-link" href="/third-party-notices" target="_blank" rel="noreferrer">OpenCodex attribution · notices</a>
    </div>
  </aside>
  <div class="backdrop" id="backdrop"></div>
  <div class="workspace">
    <header class="topbar">
      <div class="top-actions"><button class="icon-button menu-button" id="menuButton" aria-label="Open navigation">☰</button><div class="heading"><h1 id="pageTitle">Overview</h1><p id="pageSubtitle">Profile pool and runtime health at a glance</p></div></div>
      <div class="top-actions"><button class="icon-button" id="themeButton" aria-label="Change theme" title="Theme: System">◐</button><button class="button" id="refreshButton"><span>Refresh</span> ↻</button></div>
    </header>
    <main class="content">
      <section class="page" data-page="overview">
        <div class="page-head"><div><div class="eyebrow">Local control plane</div><h2>Everything ready for the next run</h2><p>Profiles, provider routes, quota, models, and runtime diagnostics stay inside Prodex.</p></div></div>
        <div class="stats">
          <div class="stat"><span class="stat-label">Profiles</span><strong class="stat-value" id="profileCount">–</strong><span class="stat-foot" id="activeProfileFoot">No active profile</span></div>
          <div class="stat"><span class="stat-label">Providers</span><strong class="stat-value" id="providerCount">–</strong><span class="stat-foot">Built-in routing adapters</span></div>
          <div class="stat"><span class="stat-label">Models</span><strong class="stat-value" id="modelCount">–</strong><span class="stat-foot">Available catalog entries</span></div>
          <div class="stat"><span class="stat-label">Quota ready</span><strong class="stat-value" id="readyCount">–</strong><span class="stat-foot" id="quotaFoot">Checking profile pool</span></div>
        </div>
        <div class="grid-2">
          <article class="card"><div class="card-head"><div><div class="card-title">Active profile</div><div class="card-subtitle">Current account used when no profile is specified</div></div><button class="button" data-go="accounts">Manage</button></div><div class="card-body stack"><div id="activeProfileCard" class="empty">Loading profile state…</div><div class="callout" id="nextStep"><strong>Preparing next step</strong><span class="muted">Loading provider state…</span></div><div id="quickCommands" class="command-grid"></div></div></article>
          <article class="card"><div class="card-head"><div><div class="card-title">Provider readiness</div><div class="card-subtitle">Configured routes in this profile pool</div></div><button class="button" data-go="providers">Configure</button></div><div class="card-body"><div class="provider-list" id="overviewProviders"><div class="empty">Loading providers…</div></div></div></article>
        </div>
      </section>

      <section class="page" data-page="providers" hidden>
        <div class="page-head"><div><div class="eyebrow">Routing</div><h2>Providers</h2><p>Inspect supported authentication paths and copy setup, launch, quota, or gateway commands.</p></div><select class="field" id="providerSelect" aria-label="Selected provider"></select></div>
        <article class="card"><div class="card-body"><div class="provider-detail" id="providerDetail"><div class="empty">Loading provider catalog…</div></div></div></article>
        <article class="card" style="margin-top:14px"><div class="card-head"><div><div class="card-title">Provider matrix</div><div class="card-subtitle">Configured profile count and available routes</div></div></div><div class="table-wrap"><table class="table"><thead><tr><th>Provider</th><th>Authentication</th><th>Default model</th><th>Profiles</th><th class="hide-sm">Routes</th></tr></thead><tbody id="providerRows"></tbody></table></div></article>
      </section>

      <section class="page" data-page="models" hidden>
        <div class="page-head"><div><div class="eyebrow">Catalog</div><h2>Models</h2><p>Filter the Prodex model catalog and copy a provider-correct launch command.</p></div><div class="toolbar"><input class="field search" id="modelSearch" type="search" placeholder="Search model or provider"><select class="field" id="modelProvider"><option value="all">All providers</option></select></div></div>
        <article class="card"><div class="card-head"><div><div class="card-title">Available models</div><div class="card-subtitle" id="modelResultCount">Waiting for catalog</div></div></div><div class="table-wrap"><table class="table"><thead><tr><th>Provider</th><th>Model</th><th>Recommended</th><th>Context</th><th class="hide-md">Capabilities</th><th>Launch</th></tr></thead><tbody id="modelRows"></tbody></table></div></article>
      </section>

      <section class="page" data-page="usage" hidden>
        <div class="page-head"><div><div class="eyebrow">Capacity</div><h2>Usage and quota</h2><p>Quota is fetched separately so slow upstream checks never block the rest of the control center.</p></div><button class="button" id="quotaRefreshButton">Refresh quota</button></div>
        <div class="stats">
          <div class="stat"><span class="stat-label">Total</span><strong class="stat-value" id="usageTotal">–</strong><span class="stat-foot">Quota-compatible profiles</span></div>
          <div class="stat"><span class="stat-label">Ready</span><strong class="stat-value good" id="usageReady">–</strong><span class="stat-foot">Can accept new work</span></div>
          <div class="stat"><span class="stat-label">Blocked</span><strong class="stat-value warn" id="usageBlocked">–</strong><span class="stat-foot">Waiting for reset</span></div>
          <div class="stat"><span class="stat-label">Errors</span><strong class="stat-value bad" id="usageErrors">–</strong><span class="stat-foot">Check auth or transport</span></div>
        </div>
        <article class="card"><div class="table-wrap"><table class="table"><thead><tr><th>Profile</th><th>Account</th><th>Status</th><th>Quota windows</th><th>Reset</th></tr></thead><tbody id="usageRows"></tbody></table></div></article>
      </section>

      <section class="page" data-page="accounts" hidden>
        <div class="page-head"><div><div class="eyebrow">Identity</div><h2>Accounts</h2><p>Create managed OpenAI profiles, switch the active profile, or remove a profile entry.</p></div></div>
        <article class="card" style="margin-bottom:14px"><div class="card-head"><div><div class="card-title">Add managed profile</div><div class="card-subtitle">Creates a profile home; authentication remains a separate login step</div></div></div><div class="card-body"><div class="form-row"><input class="field" id="profileName" placeholder="Profile name, e.g. openai-main" autocomplete="off"><button class="button primary" id="createProfileButton">Create and activate</button></div><div class="tiny muted" style="margin-top:8px">Next command: <span class="mono">prodex login --profile &lt;name&gt;</span></div></div></article>
        <article class="card"><div class="table-wrap"><table class="table"><thead><tr><th>Profile</th><th>Provider</th><th>Authentication</th><th class="hide-sm">CODEX_HOME</th><th></th></tr></thead><tbody id="accountRows"></tbody></table></div></article>
      </section>

      <section class="page" data-page="logs" hidden>
        <div class="page-head"><div><div class="eyebrow">Diagnostics</div><h2>Runtime logs</h2><p>The latest bounded log tail is read through Prodex path validation and secret redaction.</p></div><div class="toolbar"><input class="field search" id="logFilter" type="search" placeholder="Filter visible lines"><button class="button" id="logRefreshButton">Refresh logs</button></div></div>
        <article class="card"><div class="log-toolbar"><div class="log-path" id="logPath">No runtime log discovered</div></div><div class="log-list" id="logRows"><div class="empty">Loading runtime log…</div></div></article>
      </section>

      <section class="page" data-page="runtime" hidden>
        <div class="page-head"><div><div class="eyebrow">Operations</div><h2>Runtime and gateway</h2><p>Inspect resolved runtime paths and copy on-demand gateway commands.</p></div></div>
        <div class="runtime-grid" id="runtimeCards"><article class="card"><div class="empty">Loading runtime state…</div></article></div>
      </section>
    </main>
  </div>
</div>
<div class="toast" id="toast" role="status" aria-live="polite"></div>
<script>
const $=id=>document.getElementById(id);
const store={state:null,accounts:[],providers:[],models:[],usage:null,runtime:null,logs:null,coreBusy:false,usageBusy:false,lastUpdated:null,lastError:null,provider:'openai'};
const routeMeta={overview:['Overview','Profile pool and runtime health at a glance'],providers:['Providers','Authentication and routing setup'],models:['Models','Provider-aware model catalog'],usage:['Usage','Quota health across the profile pool'],accounts:['Accounts','Managed profiles and active identity'],logs:['Runtime logs','Bounded, redacted diagnostic tail'],runtime:['Runtime','Proxy and gateway operations']};
let toastTimer;

function node(tag,className,text){const value=document.createElement(tag);if(className)value.className=className;if(text!==undefined)value.textContent=text;return value}
function setText(id,value,fallback='–'){$(id).textContent=value===undefined||value===null||value===''?fallback:String(value)}
function statusClass(value){const text=String(value||'').toLowerCase();if(text.includes('ready')||text.includes('available')||text==='ok')return 'good';if(text.includes('error')||text.includes('blocked')||text.includes('exceeded')||text.includes('failed'))return 'bad';return 'warn'}
function badge(text,className=''){const value=node('span','badge '+className,text);return value}
function tableCell(text,className=''){return node('td',className,text===undefined||text===null?'–':String(text))}
function emptyRow(body,columns,message){body.replaceChildren();const row=node('tr');const cell=tableCell(message,'empty');cell.colSpan=columns;row.append(cell);body.append(row)}
function initials(value){return String(value||'P').split(/[-_.\s]+/).filter(Boolean).slice(0,2).map(part=>part[0]).join('').toUpperCase()||'P'}
function clamp(value){return Math.max(0,Math.min(100,Number(value)||0))}
function formatContext(value){return value?Number(value).toLocaleString()+' tokens':'–'}
function toast(message){const value=$('toast');value.textContent=message;value.classList.add('show');clearTimeout(toastTimer);toastTimer=setTimeout(()=>value.classList.remove('show'),2600)}
async function copyText(value){try{await navigator.clipboard.writeText(value)}catch(_){const input=node('textarea');input.value=value;input.style.position='fixed';input.style.opacity='0';document.body.append(input);input.select();document.execCommand('copy');input.remove()}toast('Copied to clipboard')}
function commandCard(label,value){const values=(Array.isArray(value)?value:[value]).filter(Boolean);const text=values.join('\n');const card=node('div','command-card');const top=node('div','command-top');top.append(node('span','command-label',label));const copy=node('button','copy-button','Copy');copy.type='button';copy.disabled=!text;copy.addEventListener('click',()=>copyText(text));top.append(copy);card.append(top,node('code','command-code',text||'Not required'));return card}
function actionButton(label,handler,className=''){const button=node('button','button '+className,label);button.type='button';button.addEventListener('click',handler);return button}

async function api(path,options={}){const headers=options.body?{'content-type':'application/json'}:{};const response=await fetch(path,{...options,headers:{...headers,...(options.headers||{})}});if(!response.ok){let message='HTTP '+response.status;try{const body=await response.json();message=body.error||message}catch(_){message=await response.text()||message}throw new Error(message)}return response.json()}
function updateConnection(){const busy=store.coreBusy||store.usageBusy;const dot=$('serverDot');dot.className='state-dot '+(busy?'busy':store.lastError?'bad':'ok');setText('serverState',busy?'Syncing':store.lastError?'Partial error':'Connected');$('refreshButton').disabled=busy;$('quotaRefreshButton').disabled=store.usageBusy;if(store.lastUpdated)setText('lastUpdated','Updated '+store.lastUpdated.toLocaleTimeString())}
async function refreshCore({quiet=false}={}){if(store.coreBusy)return;store.coreBusy=true;store.lastError=null;updateConnection();const endpoints=[['state','/api/state'],['accounts','/api/accounts'],['providers','/api/providers'],['models','/api/models'],['runtime','/api/runtime-status'],['logs','/api/logs']];let failures=0;for(const [key,path] of endpoints){try{const value=await api(path);store[key]=key==='accounts'?value.accounts||[]:key==='providers'?value.providers||[]:key==='models'?value.models||[]:value}catch(_){failures++}}store.coreBusy=false;store.lastUpdated=new Date();store.lastError=failures?failures+' dashboard endpoint(s) failed':null;renderAll();updateConnection();if(failures&&!quiet)toast(store.lastError)}
async function refreshUsage({quiet=false}={}){if(store.usageBusy)return;store.usageBusy=true;updateConnection();try{store.usage=await api('/api/usage');store.lastUpdated=new Date();renderUsage();renderOverview()}catch(error){store.lastError=error.message;if(!quiet)toast('Quota refresh failed: '+error.message)}finally{store.usageBusy=false;updateConnection()}}
async function refreshAll(options={}){if(store.coreBusy||store.usageBusy)return;await refreshCore(options);await refreshUsage(options)}

function renderAll(){renderOverview();renderProviders();renderModels();renderAccounts();renderLogs();renderRuntime();renderUsage()}
function renderOverview(){const state=store.state||{};const usage=store.usage&&store.usage.summary||{};setText('profileCount',state.profileCount);setText('providerCount',store.providers.length);setText('modelCount',store.models.length);setText('readyCount',usage.ready);setText('activeProfileFoot',state.activeProfile?'Active: '+state.activeProfile:'No active profile');setText('quotaFoot',store.usage?(usage.blocked||0)+' blocked · '+(usage.errors||0)+' errors':'Quota snapshot pending');const card=$('activeProfileCard');card.replaceChildren();const active=store.accounts.find(account=>account.active);if(active){card.className='active-profile';const avatar=node('div','avatar',initials(active.name));const detail=node('div','grow');detail.append(node('div','model-name truncate',active.name),node('div','small muted truncate',(active.providerName||active.provider)+' · '+(active.email||active.auth.label)));card.append(avatar,detail,badge('Active','good'))}else{card.className='empty';card.textContent=state.profileCount?'Choose an active profile from Accounts.':'No profiles configured yet.'}const next=$('nextStep');next.replaceChildren();const title=node('strong');const body=node('span','muted');if(!state.profileCount){title.textContent='Start with a profile';body.textContent='Create an OpenAI profile in Accounts, or choose another provider setup path.'}else if(active){title.textContent='Ready to launch';body.textContent='Use a model command below or run prodex s with the active '+(active.providerName||active.provider)+' profile.'}else{title.textContent='Select an active profile';body.textContent='Profiles exist, but none currently owns default launches.'}next.append(title,body);const commands=$('quickCommands');commands.replaceChildren();const commandState=state.commands||{};commands.append(commandCard('Open control center',commandState.open||'prodex gui'),commandCard('Quota snapshot',commandState.quota||'prodex quota --all --once'));const list=$('overviewProviders');list.replaceChildren();if(!store.providers.length){list.append(node('div','empty','No providers available.'));return}store.providers.forEach(provider=>{const row=node('div','provider-mini');row.append(node('span','provider-dot '+(provider.active?'active':'')));const detail=node('div','grow');detail.append(node('div','model-name',provider.label),node('div','tiny muted',(provider.configuredProfiles||0)+' profiles · '+(provider.defaultModel||'no default model')));row.append(detail,badge(provider.active?'Active':provider.configuredProfiles?'Configured':'Available',provider.active?'good':''));list.append(row)})}

function syncProviderFilters(){const select=$('providerSelect');const current=store.providers.some(provider=>provider.id===store.provider)?store.provider:(store.providers[0]&&store.providers[0].id)||'openai';store.provider=current;select.replaceChildren();store.providers.forEach(provider=>{const option=node('option','',provider.label);option.value=provider.id;select.append(option)});select.value=current;const filter=$('modelProvider');const previous=filter.value||'all';filter.replaceChildren();const all=node('option','','All providers');all.value='all';filter.append(all);store.providers.forEach(provider=>{const option=node('option','',provider.label);option.value=provider.id;filter.append(option)});filter.value=store.providers.some(provider=>provider.id===previous)?previous:'all'}
function renderProviders(){syncProviderFilters();const detail=$('providerDetail');detail.replaceChildren();const provider=store.providers.find(value=>value.id===store.provider);if(!provider){detail.append(node('div','empty','No provider data available.'));emptyRow($('providerRows'),5,'No providers available.');return}const summary=node('div','provider-summary');summary.append(node('div','eyebrow',provider.id),node('h3','',provider.label),node('p','',provider.notes||'Provider route available through Prodex.'));const badges=node('div','badge-row');badges.append(badge((provider.configuredProfiles||0)+' profiles',provider.configuredProfiles?'good':''),badge(provider.auth||'Auth varies'),badge(provider.defaultModel||'No default model'));summary.append(badges);const commands=node('div','command-grid');const values=provider.commands||{};commands.append(commandCard('Setup / import',values.setup),commandCard('Launch',values.launch),commandCard('Quota',values.quota),commandCard('Gateway',values.gateway));detail.append(summary,commands);const rows=$('providerRows');rows.replaceChildren();store.providers.forEach(value=>{const row=node('tr');row.addEventListener('click',()=>{store.provider=value.id;$('providerSelect').value=value.id;renderProviders()});const name=tableCell(value.label+(value.active?' · active':''),value.active?'good':'');row.append(name,tableCell(value.auth),tableCell(value.defaultModel),tableCell(value.configuredProfiles||0));const routes=tableCell('','hide-sm');(value.availableThrough||[]).forEach(route=>routes.append(badge(route)));row.append(routes);rows.append(row)})}

function renderModels(){const provider=$('modelProvider').value||'all';const query=$('modelSearch').value.trim().toLowerCase();let models=store.models.filter(model=>(provider==='all'||model.provider===provider)&&(!query||[model.id,model.display_name,model.providerName,model.provider].some(value=>String(value||'').toLowerCase().includes(query))));const total=models.length;models=models.slice(0,150);setText('modelResultCount',total+(total===1?' result':' results')+(total>models.length?' · first 150 shown':''));const rows=$('modelRows');rows.replaceChildren();if(!models.length){emptyRow(rows,6,store.models.length?'No models match this filter.':'No model catalog available.');return}models.forEach(model=>{const row=node('tr');row.append(tableCell(model.providerName||model.provider));const identity=tableCell('');identity.append(node('div','model-name',model.display_name||model.id),node('div','model-id',model.id));row.append(identity);const recommended=tableCell('');if(model.recommended)recommended.append(badge('Recommended','good'));row.append(recommended,tableCell(formatContext(model.context_window)));const capabilities=tableCell('','hide-md');[...(model.endpoints||[]),...Object.entries(model.feature_flags||{}).filter(([,enabled])=>enabled).map(([name])=>name)].forEach(value=>capabilities.append(badge(value)));row.append(capabilities);const launch=tableCell('','command-cell');const text=model.launchCommand||'–';launch.append(node('div','command-code',text));const copy=actionButton('Copy',()=>copyText(text));copy.style.marginTop='6px';launch.append(copy);row.append(launch);rows.append(row)})}

function quotaWindow(label,window){const wrap=node('div','quota-window');const meta=node('div','quota-meta');const used=clamp(window&&window.usedPercent);meta.append(node('span','',label),node('span','',window?used.toFixed(0)+'% used':'–'));const track=node('div','quota-track');const fill=node('div','quota-fill '+(used>=90?'bad':used>=70?'warn':''));fill.style.width=used+'%';track.append(fill);wrap.append(meta,track);return wrap}
function renderUsage(){const summary=store.usage&&store.usage.summary||{};setText('usageTotal',summary.total);setText('usageReady',summary.ready);setText('usageBlocked',summary.blocked);setText('usageErrors',summary.errors);setText('readyCount',summary.ready);const rows=$('usageRows');rows.replaceChildren();const profiles=store.usage&&store.usage.profiles||[];if(!profiles.length){emptyRow(rows,5,store.usage?'No quota-compatible profiles configured.':'Quota snapshot is loading…');return}profiles.forEach(profile=>{const quota=profile.quota||{};const row=node('tr');row.append(tableCell(profile.name+(profile.active?' · active':''),profile.active?'good':''),tableCell(quota.account||profile.workspaceId));const status=tableCell('');status.append(badge(quota.status||'Unknown',statusClass(quota.status)));row.append(status);const windows=tableCell('');const windowData=quota.windows||{};if(windowData.fiveHour||windowData.weekly){windows.append(quotaWindow('5 hour',windowData.fiveHour),quotaWindow('Weekly',windowData.weekly))}else windows.append(node('span','muted small',quota.main||'–'));row.append(windows,tableCell(quota.reset));rows.append(row)})}

function renderAccounts(){const rows=$('accountRows');rows.replaceChildren();if(!store.accounts.length){emptyRow(rows,5,'No profiles configured. Create one above or use a provider setup command.');return}store.accounts.forEach(account=>{const row=node('tr');const identity=tableCell('');identity.append(node('div','model-name',account.name+(account.active?' · active':'')),node('div','tiny muted',account.email||'No account email'));row.append(identity,tableCell(account.providerName||account.provider));const auth=tableCell('');auth.append(badge(account.auth.label+(account.auth.quotaCompatible?' · quota':'')));row.append(auth,tableCell(account.codexHome,'hide-sm'));const actions=tableCell('');actions.className='row-actions';const use=actionButton(account.active?'Active':'Use',async()=>{try{use.disabled=true;await api('/api/profile/active',{method:'POST',body:JSON.stringify({profile:account.name})});toast(account.name+' is now active');await refreshCore()}catch(error){toast('Activation failed: '+error.message)}finally{use.disabled=false}},account.active?'primary':'');use.disabled=account.active;const remove=actionButton('Remove',async()=>{if(!confirm('Remove profile entry '+account.name+'? Managed files are kept.'))return;try{remove.disabled=true;await api('/api/profile/'+encodeURIComponent(account.name),{method:'DELETE'});toast('Removed '+account.name);await refreshAll()}catch(error){toast('Remove failed: '+error.message)}finally{remove.disabled=false}},'danger');actions.append(use,remove);row.append(actions);rows.append(row)})}

function renderLogs(){const data=store.logs||{};setText('logPath',data.path,'No runtime log discovered');const filter=$('logFilter').value.trim().toLowerCase();const all=data.lines||[];const visible=all.map((line,index)=>({line,index})).filter(value=>!filter||value.line.toLowerCase().includes(filter));const rows=$('logRows');rows.replaceChildren();if(!visible.length){rows.append(node('div','empty',all.length?'No log lines match this filter.':'No runtime log lines available.'));return}visible.forEach(value=>{const lower=value.line.toLowerCase();const level=lower.includes('error')||lower.includes('failed')||lower.includes('overloaded')?'bad':lower.includes('warn')||lower.includes('backoff')?'warn':'';const row=node('div','log-line '+level);row.append(node('span','log-number',value.index+1),node('span','',value.line));rows.append(row)});rows.scrollTop=rows.scrollHeight}

function detailRow(label,value){const row=node('div','detail-row');row.append(node('div','detail-key',label),node('div','detail-value mono',value||'–'));return row}
function renderRuntime(){const root=$('runtimeCards');root.replaceChildren();const runtime=store.runtime&&store.runtime.runtime;const gateway=store.runtime&&store.runtime.gateway;if(!runtime||!gateway){root.append(node('article','card empty','Runtime state is loading…'));return}const runtimeCard=node('article','card');const runtimeHead=node('div','card-head');runtimeHead.append(node('div','card-title','Runtime proxy'),badge(runtime.status,statusClass(runtime.status)));const runtimeBody=node('div','card-body detail-list');runtimeBody.append(detailRow('Log directory',runtime.logDir),detailRow('Latest pointer',runtime.latestLogPointer),detailRow('Latest log',runtime.latestLog),detailRow('Doctor',runtime.doctorCommand));runtimeCard.append(runtimeHead,runtimeBody);const gatewayCard=node('article','card');const gatewayHead=node('div','card-head');gatewayHead.append(node('div','card-title','Gateway'),badge(gateway.status,statusClass(gateway.status)));const gatewayBody=node('div','card-body command-grid');gatewayBody.append(commandCard('Start',gateway.startCommand),commandCard('Providers',gateway.providersCommand),commandCard('Models',gateway.modelsCommand));gatewayCard.append(gatewayHead,gatewayBody);root.append(runtimeCard,gatewayCard)}

function currentRoute(){const value=location.hash.replace(/^#/,'');return routeMeta[value]?value:'overview'}
function applyRoute(){const route=currentRoute();document.querySelectorAll('[data-page]').forEach(page=>page.hidden=page.dataset.page!==route);document.querySelectorAll('[data-route]').forEach(button=>button.setAttribute('aria-current',button.dataset.route===route?'page':'false'));const meta=routeMeta[route];setText('pageTitle',meta[0]);setText('pageSubtitle',meta[1]);closeMenu();if(route==='logs'&&store.logs)renderLogs()}
function go(route){location.hash=route;applyRoute()}
function openMenu(){$('rail').classList.add('open');$('backdrop').classList.add('open')}
function closeMenu(){$('rail').classList.remove('open');$('backdrop').classList.remove('open')}
const themes=['system','light','dark'];function setTheme(theme){document.documentElement.dataset.theme=theme;localStorage.setItem('prodex-theme',theme);$('themeButton').title='Theme: '+theme[0].toUpperCase()+theme.slice(1);$('themeButton').textContent=theme==='light'?'☀':theme==='dark'?'●':'◐'}
function cycleTheme(){const current=document.documentElement.dataset.theme||'system';setTheme(themes[(themes.indexOf(current)+1)%themes.length])}

document.querySelectorAll('[data-route]').forEach(button=>button.addEventListener('click',()=>go(button.dataset.route)));
document.querySelectorAll('[data-go]').forEach(button=>button.addEventListener('click',()=>go(button.dataset.go)));
$('providerSelect').addEventListener('change',event=>{store.provider=event.target.value;renderProviders()});
$('modelProvider').addEventListener('change',renderModels);$('modelSearch').addEventListener('input',renderModels);$('logFilter').addEventListener('input',renderLogs);
$('refreshButton').addEventListener('click',()=>refreshAll());$('quotaRefreshButton').addEventListener('click',()=>refreshUsage());$('logRefreshButton').addEventListener('click',()=>refreshCore());
$('createProfileButton').addEventListener('click',async()=>{const name=$('profileName').value.trim();if(!name){toast('Enter a profile name first');return}const button=$('createProfileButton');try{button.disabled=true;const result=await api('/api/profile',{method:'POST',body:JSON.stringify({name,activate:true})});$('profileName').value='';toast('Created '+result.profile+'. Run prodex login --profile '+result.profile);await refreshAll()}catch(error){toast('Create failed: '+error.message)}finally{button.disabled=false}});
$('profileName').addEventListener('keydown',event=>{if(event.key==='Enter')$('createProfileButton').click()});$('themeButton').addEventListener('click',cycleTheme);$('menuButton').addEventListener('click',openMenu);$('backdrop').addEventListener('click',closeMenu);window.addEventListener('hashchange',applyRoute);window.addEventListener('keydown',event=>{if(event.key==='Escape')closeMenu()});document.addEventListener('visibilitychange',()=>{if(!document.hidden&&(!store.lastUpdated||Date.now()-store.lastUpdated.getTime()>10000))refreshAll({quiet:true})});
setTheme(themes.includes(localStorage.getItem('prodex-theme'))?localStorage.getItem('prodex-theme'):'system');applyRoute();refreshAll();setInterval(()=>{if(!document.hidden)refreshAll({quiet:true})},10000);
</script>
</body>
</html>"##;
